// @ts-ignore generated by `opennextjs-cloudflare build`; absent in a fresh checkout
import { default as handler } from "./.open-next/worker.js"

interface CronEnv {
    CRON_SECRET?: string
}

interface ScheduledController {
    cron: string
    scheduledTime: number
}

interface Ctx {
    waitUntil(promise: Promise<unknown>): void
}

const worker = {
    fetch: handler.fetch,

    async scheduled(controller: ScheduledController, env: CronEnv, ctx: Ctx) {
        const mode =
            controller.cron === "0 5 * * SUN" ? "full" : "incremental"

        const request = new Request(
            `https://project-sonam.internal/api/sync?mode=${mode}`,
            { headers: { authorization: `Bearer ${env.CRON_SECRET ?? ""}` } }
        )

        ctx.waitUntil(
            handler
                .fetch(request, env, ctx)
                .then((res: Response) =>
                    console.log(`[cron] sync mode=${mode} -> ${res.status}`)
                )
                .catch((err: unknown) =>
                    console.error(`[cron] sync mode=${mode} failed`, err)
                )
        )
    },
}

export default worker
